spring:
  application:
    name: library-system
  datasource:
    url: jdbc:mysql://localhost:3307/librarydb
    username: dragon
    password: dragon123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true