name: Java CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Repository letöltése
        uses: actions/checkout@v4

      - name: Java 21 beállítása
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Projekt build + tesztek
        run: mvn clean verify